# Site settings

title: Herculino Trotta
url: "https://eitchtee.github.io"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""

bio-page-label-pt: Curr√≠culo
projects-page-label-pt: Projetos
essays-page-label-pt: Blog

bio-page-label-en: CV
projects-page-label-en: Projects
essays-page-label-en: Blog

theme-bio: bio.html
theme-home: home.html
theme-projects: projects.html
theme-essays: essays.html

projects-url-pt: projetos
essays-url-pt: blog
bio-url-pt: curriculo

projects-url-en: projects
essays-url-en: blog
bio-url-en: cv

# Specify the rouge syntax highlighter theme. Pick one from css/rouge.
rouge-theme: base16.dark

# YOU NORMALLY NEVER CHANGE THE FOLLOWING
markdown: kramdown
include: [_data]

